server:
  port: 9500

spring:
  application:
    name: ribbon-consumer

eureka:
  instance:
    hostname: localhost # 主机名
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# 配置 ribbon 负载均衡策略
ribbon-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule