server:
  port: 9000

eureka:
  instance:
    hostname: localhost # 主机名
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}

  client:
    service-url:
      defaultZone: http://eureka-server-ha1:8771/eureka, http://eureka-server-ha2:8772/eureka # eureka服务端地址，将来客户端使用该地址和eureka进行通信

spring:
  application:
    name: eureka-consumer # 设置当前应用的名称。将来会在eureka中Application显示。将来需要使用该名称来获取路径