server:
  port: 7010

spring:
  application:
    name: config-server
  # spring cloud config
  cloud:
    config:
      server:
        # git 的 远程仓库地址
        git:
          # 使用 http 连接远程 git
          uri: https://github.com/Tristrami/config-demo.git
          username: Tristrami
          password: ltr20001121
      label: main # 分支配置

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
